### PR TITLE
add gsclassic.png and update other station png files better compression

### PR DESCRIPTION
**Pull request by jeffmcneill**
Solves https://github.com/cheshire137/soma-chrome/issues/45

### CODE REVIEW

**Comment by rustyhodge** [comment]
Those images really should be loaded from our site.

**Comment by jeffmcneill** [comment]
@rustyhodge The images on the site come in a variety of formats for different sizes. There is no consistency whether a given image is .jpg or .png for a given size and a given station. I definitely agree with you, but it would add not only complexity but additional load time to fetch images from the website. Also, image sizes are not optimized on the site. To get a png file for gslcassic I had to convert a jpg file and then compress the image with external tools. The image has been broken in this chrome extension since the appearance of the station gsclassic (my personal favorite). This merge request will fix that problem.

**Comment by rustyhodge** [comment]
Tell me what sizes you need and I’ll make sure they’re in the website. We won’t over compress images if we think it makes them look bad. But tell me your ideal sizes/formats. 

We also change / add images as  necessary.

**Comment by cheshire137** [comment]
Dang, y’all don’t even need me. 😄 Thank you for the pull request! I’m all right waiting for Rusty to add some images on his end before landing this branch.

**Comment by jeffmcneill** [comment]
@rustyhodge the images used in the chrome extension are 120x120px png. However, your [channel xml feed](https://somafm.com/channels.xml) has a mix of png and jpg at that size. There is no consistency also with the naming of a given image. E.g., the Suburbs of Goa channel is suburbsofgoa but the 120px image is sog120.jpg; Space Station Soma is spacestation and sss.jpg. All the larger images are generally named after the station, but the 120px default images are not necessarily. The images sizes are fine on the site, at least for the half dozen I looked at. 

The thing is, every time a browser starts up, do you really want to have the xml file and 39 images requested? Having them packed in a simple chrome extension will keep its memory load and network latency low.

**Comment by rustyhodge** [comment]
Why does the name of the file matter if it's referenced in the channels.xml/.json file? In theory they could be random strings. We change images and update images 

And why can't you cache the images, and see if they've been updated since last time it was opened? We send the Last-Updated time in the http header. But you will also need to check for files that have changed, and we swap things out sometimes as well.

And yeh I do want it checking for updated images every time it is opened. It's not different from opening our website front page.

There is a mix of PNG and JPG because we thought some looked better as JPGs and the PNG24s were too big. There might be some exceptions, like indychick.jpg ideally would be a PNG.

I hope you're checking the channels file when the extension is launched; stations come and go and that's the only way to know what's available.

**Comment by jeffmcneill** [comment]
All I want is to have the gsclassic image show up and not a "broken image"
image. I looked at the images already in the extension and saw that they
could have some lossless compression on them. If that is not ok, then that
is pretty sad because no one is going to rewrite the application to get the
images pulled from the website. And yes, it would make chrome slower and
consume more memory, which no one wants.

Sincerely,
Jeff Mcneill
https://mcneill.io

**Comment by rustyhodge** [comment]
Jeff
 
I'm very disappointed in your response and attitude.

You are including our copyrighted images in an extension that you are putting up with a MIT free to distribute and use for commercial purposes licenses. 

** We do not grant permission for our copyrighted and/or trademarked logos to be distributed this way (with the app/extension) **

Here's my suggestion: Remove the icons altogether in that case.

Speeds up the load. Doesn't show icons that we don't have control over.

I apologize for not paying attention to what was happening earlier; I had always assumed like other apps, everything was being loaded based on our channels file. Had I know I would have brought this up a long time ago with Sarah.

Sincerely
Rusty Hodge
SomaFM

**Pull request closed without merging**
